trigger:
  - main
pool:
name: "WKL-npbxmzkwof3998151" # Specifies the self-hosted agent pool
steps:
- script: |
    sudo apt-get update -y
    sudo apt-get install git -y # Install Git if not already available
displayName: 'Install Git'
- script: |
    # Install Python 3.11 if not installed
    sudo apt install python3
displayName: 'Install Python 3.11 if not present'
- script: |
    python3 test.py # Run python File
  displayName: 'Run test.py'
